### ISSUE TITLE
Mac OS 与 Ubuntu下微信聊天窗口的字体特别大

### ISSUE THREAD

**Issue by ttym** [Jamling/SmartIM4IntelliJ#62]
RT.Mac OS 与 Ubuntu下微信聊天窗口的字体特别大
请问在哪里可以调整聊天窗口的字体大小？

**Comment by Jamling** [comment]
字体大小为IDE默认字体，我在mac下看着挺正常的，发个截图让我看看你的。

**Comment by ttym** [comment]
大概是这样的
![image](https://user-images.githubusercontent.com/3234290/55855819-190f4380-5b9b-11e9-99e1-e8a4183529d1.png)


> 字体大小为IDE默认字体，我在mac下看着挺正常的，发个截图让我看看你的。

**Comment by Jamling** [comment]
聊天窗口是使用html的，基础样式是我写死在源代码中的，考虑到扩展性，我在2.6.X的版本以前加载了一个在线css，不过我注意到在swing中加载css是一个同步过程，会导致打开聊天窗口变得很慢，所以我在其后的版本中注释掉了在线css样式加载。这导致样式无法再修改，除非我发布新版本。

**Comment by ttym** [comment]
> 聊天窗口是使用html的，基础样式是我写死在源代码中的，考虑到扩展性，我在2.6.X的版本以前加载了一个在线css，不过我注意到在swing中加载css是一个同步过程，会导致打开聊天窗口变得很慢，所以我在其后的版本中注释掉了在线css样式加载。这导致样式无法再修改，除非我发布新版本。

我觉得可以考虑在后续版本把css样式放出来，通过加载用户自定义配置来实现样式自定义
不然每次这么大字体太引人瞩目了😭

**Comment by Jamling** [comment]
v2.7.0 已引入样式自定义功能，在设置->聊天窗口样式中，可以先加载默认配置，修改`div`中的`font-size`属性值后再保存。

```css
/*聊天记录格式*/
/* <div>                                     */
/*    <span class="sender|my">               */
/*      <span class="time">HH:mm:ss</span>   */
/*      <a href="user://sender">sender</a>:  */
/*    </span>                                */
/*    <span class="content">Content</span>   */
/* </div>                                    */
div {/*字体大小，Swing中无法设置body字体大小，只好在这里设置了*/
    font-size: 14pt;
}
.sender { /*发送人*/
    display: inline;
    float: left;
}
...
```
